- name: Update repositories on Ubuntu
  become: yes
  apt:
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install keepalived on Ubuntu
  become: yes
  apt:
    name: keepalived
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Enable keepalived service
  become: yes
  service:
    name: keepalived
    enabled: yes

- name: Configure keepalived on ubuntu
  notify: Restart keepalived svc
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
